Steph branch
spfave/neighborhood-handyman pull request #24
Opened 2021-07-24 17:45 UTC by whatawhat

2021-07-24 18:32 UTC, Captain63 commented on client/src/pages/Account.js
>    if (!profile?.name) {
We don't need this since they can't reach this page without being signed in

2021-07-24 18:33 UTC, Captain63 requested changes
See comment. Also make sure you have pulled the latest version of main and merged. I couldn't recreate the previous error after pulling main, so that should fix the issue

2021-07-25 21:51 UTC, whatawhat commented
I removed that part out of my code. I also made sure I pulled and merged the latest version.

2021-07-25 21:51 UTC, Captain63 approved these changes
Looking good.

2021-07-25 21:51 UTC, merged